export default {
    LOGIN: 'Connexion',
    LOGINFORGETPASSWORD: 'Mot de passe oublié',
    MESSAGESENDMAILCHANGINGPASSWORD: '../screens/screens/ScreenMessageSendMailChangingMdp',
    REGISTERCANDIDATE: '../screens/screens/ScreenRegisterCandidate',
    CREATEPROFILECANDIDATE: '../screens/screens/ScreenCreateProfileCandidate',
    CANDIDATEPAGINATIONONE: '../screens/screens/ScreenEditProfileCandidate/ScreenCandidatePaginationPartOne',
    CANDIDATEPAGINATIONTWO: '../screens/screens/ScreenEditProfileCandidate/ScreenCandidatePaginationPartTwo',
    CANDIDATEPAGINATIONTHREE: '../screens/screens/ScreenEditProfileCandidate/ScreenCandidatePaginationPartThree',
    DRAWERLAYOUTMENUCANDIDATE: '../screens/screens/DrawerLayoutMenuCandidate',
    MESSAGEDITPROFILE: '../screens/screens/ScreenMessageEditProfile',
    REGISTERECRUITER: '../screens/screens/ScreenRegisterRecruiter',
    CREATEPROFILERECRUITER: '../screens/screens/ScreenCreateProfileRecruiter',
    MESSAGECREATEPROFILE: '../screens/screens/ScreenMessageCreateProfile',
    PROFILECANDIDATE: '../screens/screens/ScreenProfileCandidate',
    CANDIDATEPAGINATIONPARTONE: '../screens/screens/ScreenEditProfileCandidate/ScreenCandidatePaginationPartOne',
    CANDIDATEPAGINATIONPARTWO: '../screens/screens/ScreenEditProfileCandidate/ScreenCandidatePaginationPartTwo',
    CANDIDATEPAGINATIONPARTTHREE: '../screens/screens/ScreenEditProfileCandidate/ScreenCandidatePaginationPartThree',
    PROFILRECRUITER: '../screens/screens/ScreenProfileRecruiter',
    PAGINATIONPARTRECRUITERONE: '../screens/screens/ScreenEditProfileRecruiter/ScreenPaginationPartRecruiterOne',
    PAGINATIONPARTRECRUITERTWO: '../screens/screens/ScreenEditProfileRecruiter/ScreenPaginationPartRecruiterOne',
    PAGINATIONPARTRECRUITERTHREE: '../screens/screens/ScreenEditProfileRecruiter/ScreenPaginationPartRecruiterThree',
    SEARCHPROFILESCANDIDATES: '../screens/screens/ScreenSearchProfilesCandidates',
    SEEPROFILECANDIDATE: '../screens/screens/ScreenSearchProfilesCandidates/SeeProfileCandidate',
    PROFILESELECTED: '../screens/screens/ScreenSearchProfilesCandidates/ScreenProfileSelected',
    CONTACTCANDIDATES: '../screens/screens/ScreenSearchProfilesCandidates/ContactCandidates',
    DRAWERLAYOUTRECRUITER: '../screens/screens/DrawerLayoutMenuRecruiter',
    SENDMESSAGESUCCESSFULLY: '../screens/screens/ScreenSendMessageSuccessfully',
    MESSAGELOGOUTACCOUNTPROFILE: '../screens/screens/ScreenMessageLogoutAccountProfile',
}
